[project]
name = "twin-prime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "matplotlib>=3.10.3",
    "notebook>=7.4.4",
    "pip>=25.1.1",
    "scipy>=1.16.0",
    "sympy>=1.14.0",
]
